"""Whether a group's `sound_name` is usable for a *supplementary* clockworks search, once the
LLM pre-filter (`prefilter.py`) has already picked canonical example videos via known URLs
(clockworks' `postURLs` input -- see DISCOVER.md).

**2026-09-18: hashtag- and keyword-based search anchors are removed entirely, not kept as
dead code** -- the live `anchor_inspection.md` diagnostic showed hashtag anchors matched
their own pulled videos only 18% of the time (0/N for three trends), and keyword search
returned near-random content. Sound-based search was the one method that worked reliably
(5/5 hit rate on "Deep breaths, honey") and is the only one that survives, now as an
*optional supplement* to the canonical URL fetch rather than the primary anchor. See
DISCOVER.md's "Why hashtag/keyword search was dropped" for the full evidence.

Real finding this logic already encoded and still applies: most user-generated TikTok sounds
aren't searchable song titles, they're autogenerated labels like "original sound - Jordan"
(the uploader's username, not a title) -- searching TikTok for that literal string doesn't
reliably surface videos using the trend. Named commercial tracks (e.g. "FREAKED OUT — Fat
Papi", "Alibi — Sevdaliza") don't have this problem, so a generic "original sound..." label
is treated as unusable for search (still fine to display/record as context, just not to
query with).
"""
from __future__ import annotations

import re

_GENERIC_SOUND_RE = re.compile(r"^original sound\b", re.IGNORECASE)


def is_sound_searchable(sound_name: str | None) -> bool:
    """True if sound_name is a real, specific-enough string to hand to clockworks'
    searchQueries input as a supplementary search -- false for null/empty or a generic
    autogenerated "original sound - <user>" label."""
    if not sound_name or not sound_name.strip():
        return False
    return not _GENERIC_SOUND_RE.match(sound_name.strip())
